# Generated by Django 4.2.7 on 2023-12-13 22:44

import chatserver.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chatserver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=chatserver.models.category_icon_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_server",
                to="chatserver.server",
            ),
        ),
    ]
