# Generated by Django 4.2.7 on 2023-12-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatserver", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
